
name: nekosama
description: Unofficial dart api for neko-sama.fr.
version: 2.3.0
homepage: https://github.com/zkayia/nekosama_dart
issue_tracker: https://github.com/zkayia/nekosama_dart/issues
repository: https://github.com/zkayia/nekosama_dart

publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  collection: ^1.16.0
  html: ^0.15.0
