
name: nekosama_dart
repository: https://github.com/zkayia/nekosama_dart

packages:
  - packages/**

command:
  bootstrap:
    usePubspecOverrides: true

ide:
  intellij: false

scripts:
  unused:
    run: dart pub run dart_code_metrics:metrics check-unused-code lib && dart pub run dart_code_metrics:metrics check-unused-files lib
    exec:
      concurrency: 1