
name: nekosama_hive
description: Unofficial dart api for neko-sama.fr with Hive powered search.
version: 2.1.0
homepage: https://github.com/zkayia/nekosama_dart
issue_tracker: https://github.com/zkayia/nekosama_dart/issues
repository: https://github.com/zkayia/nekosama_dart

publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  hive: ^2.2.3
  nekosama:
    git:
      url: https://github.com/zkayia/nekosama_dart
      path: packages/nekosama
